adminPassword: admin

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
